/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-15 16:14:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1583844248000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Mypage</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main/afterLoginCommon.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/5e1e16b3f4.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/748cfe3a61.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Fredoka+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main/mypage.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/mainInclude.jsp", out, false);
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("        <article class=\"first\">\r\n");
      out.write("            <div class=\"intro-div\">\r\n");
      out.write("                <div class=\"img-div\">\r\n");
      out.write("              \t  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/upload/member/frofileimg/ex2.jpg\" alt=\"\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"myname-div font-kor\">\r\n");
      out.write("                    <div style=\"font-size: 25px;margin:0 10% \">@wingStudy_02</div>\r\n");
      out.write("                    <div style=\"font-size:30px;font-weight: 900;margin:5% 20% 0 30%\" >스테파니</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btn-div\">\r\n");
      out.write("                <input type=\"button\" value=\"회원정보 수정\" class=\"update-btn font-kor\">\r\n");
      out.write("                <input type=\"button\" value=\"프로필 카드\" class=\"update-btn font-kor\" \r\n");
      out.write("                \t\tonclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/frofile.do'\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"list-div\">\r\n");
      out.write("                <div class=\"list-title\">\r\n");
      out.write("                    <p style=\"color: white;font-size: 20px;font-weight: bold; padding: 6%;\" class=\"font-kor\">소모임 목록</p>\r\n");
      out.write("                    <div class=\"list-ul-container\">\r\n");
      out.write("                        <ul class=\"font-kor list-ul\" style=\"padding: 0;\">\r\n");
      out.write("                            <li><p class=\"p-class\">윙스터디 모임</p></li>\r\n");
      out.write("                            <li><p class=\"p-class\">윙스터디</p></li>\r\n");
      out.write("                            <li><p class=\"p-class\">윙</p></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <article class=\"second\">\r\n");
      out.write("            <div class=\"notice-container\">\r\n");
      out.write("                <div class=\"notice-title font-kor\">\r\n");
      out.write("                    <i class=\"fas fa-bell\" style=\"font-size:25px;color: #2756a6;margin:5% 5% 2% 0;\"></i><span style=\"font-size:25px;\">알림</span></div>\r\n");
      out.write("                <div class=\"contents\">\r\n");
      out.write("                    <div class=\"content font-kor\">\r\n");
      out.write("                        <p class=\"p-content\">윙 스터디에 가입신청이 승인되었습니다.</p>\r\n");
      out.write("                        <p class=\"p-content\">김원재님에게 친구신청이 왔습니다. <input type=\"button\" value=\"수락\" class=\"friend-btn font-kor\"></p>\r\n");
      out.write("                        <p class=\"p-content\">신형철님에게 친구신청이 왔습니다. <input type=\"button\" value=\"수락\" class=\"friend-btn font-kor\"></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"board-div\">\r\n");
      out.write("                <div class=\"board-title\">\r\n");
      out.write("                    <i class=\"fas fa-pencil-alt\" style=\"font-size:25px;color: #2756a6;margin:5% 4% 2% 0;\"></i><span class=\"font-kor\" style=\"font-size:25px;\">내가 쓴 게시글</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"board-contents font-kor\">\r\n");
      out.write("                    <ul style=\"font-size: 30px;\">\r\n");
      out.write("                        <li style=\"color: #2756a6;\">\r\n");
      out.write("                            <div class=\"board-content\">\r\n");
      out.write("                                <div class=\"board-con\">\r\n");
      out.write("                                    <p class=\"p-board\" style=\"color: #2756a6; font-weight: bolder;\">윙스터디 모임</p>\r\n");
      out.write("                                    <p class=\"p-board bold-font\" >이번주 금요일 스터디 일정입니다.</p>\r\n");
      out.write("                                    <p class=\"p-board\" style=\"font-size: 15px; padding-top: 2%;\">작성일 : 2020-20-20</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"board-btn\">\r\n");
      out.write("                                    <input type=\"button\" value=\"댓글보기\" class=\"reply-btn font-kor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li style=\"color: #2756a6;\">\r\n");
      out.write("                            <div class=\"board-content\">\r\n");
      out.write("                                <div class=\"board-con\">\r\n");
      out.write("                                    <p class=\"p-board\" style=\"color: #2756a6; font-weight: bolder;\">윙스터디 모임</p>\r\n");
      out.write("                                    <p class=\"p-board bold-font\" >이번주 금요일 스터디 일정입니다.</p>\r\n");
      out.write("                                    <p class=\"p-board\" style=\"font-size: 15px; padding-top: 2%;\">작성일 : 2020-20-20</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"board-btn\">\r\n");
      out.write("                                    <input type=\"button\" value=\"댓글보기\" class=\"reply-btn font-kor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li style=\"color: #2756a6;\">\r\n");
      out.write("                            <div class=\"board-content\">\r\n");
      out.write("                                <div class=\"board-con\">\r\n");
      out.write("                                    <p class=\"p-board\" style=\"color: #2756a6; font-weight: bolder;\">윙스터디 모임</p>\r\n");
      out.write("                                    <p class=\"p-board bold-font\">이번주 금요일 스터디 일정입니다.</p>\r\n");
      out.write("                                    <p class=\"p-board\" style=\"font-size: 15px; padding-top: 2%;\">작성일 : 2020-20-20</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"board-btn\">\r\n");
      out.write("                                    <input type=\"button\" value=\"댓글보기\" class=\"reply-btn font-kor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li style=\"color: #2756a6;\">\r\n");
      out.write("                            <div class=\"board-content\">\r\n");
      out.write("                                <div class=\"board-con\">\r\n");
      out.write("                                    <p class=\"p-board\" style=\"color: #2756a6; font-weight: bolder;\">윙스터디 모임</p>\r\n");
      out.write("                                    <p class=\"p-board bold-font\" >이번주 금요일 스터디 일정입니다.</p>\r\n");
      out.write("                                    <p class=\"p-board\" style=\"font-size: 15px; padding-top: 2%;\">작성일 : 2020-20-20</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"board-btn\">\r\n");
      out.write("                                    <input type=\"button\" value=\"댓글보기\" class=\"reply-btn font-kor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <article class=\"third\">\r\n");
      out.write("            <div class=\"friend-container\">\r\n");
      out.write("                <div class=\"friend-title font-kor\"><p style=\"color: white;font-size: 20px;font-weight: bold;padding: 6%;\">친구 목록</p></div>\r\n");
      out.write("                <div class=\"friend-lists\">\r\n");
      out.write("                    <div class=\"friend-list\">\r\n");
      out.write("                        <div class=\"friend-img\">\r\n");
      out.write("                        \t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/upload/member/frofileimg/ex2.jpg\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"friend-name font-kor\">김원재</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"friend-list\">\r\n");
      out.write("                        <div class=\"friend-img\">\r\n");
      out.write("                        \t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/upload/member/frofileimg/ex2.jpg\" alt=\"\" />\t\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"friend-name font-kor\">신형철</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"friend-list\">\r\n");
      out.write("                        <div class=\"friend-img\">\r\n");
      out.write("                        \t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/upload/member/frofileimg/ex2.jpg\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"friend-name font-kor\">백동준</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </section>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
