/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-15 12:33:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class selectCategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1583844248000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>selectPage</title>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("    <link href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    @font-face { font-family: 'GmarketSansLight'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansLight.woff') format('woff'); font-weight: normal; font-style: normal; }\r\n");
      out.write("\r\n");
      out.write("    body{\r\n");
      out.write("        margin: 0;        \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #container {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        background-image: url(\"../resources/images/selectcate/bmg.png\");\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        /* min-width: 1080px;\r\n");
      out.write("        max-width: 1920px; */\r\n");
      out.write("        /* width: 1080px !important;\r\n");
      out.write("        height: 1920px !important; */\r\n");
      out.write("        width: 1920px !important;\r\n");
      out.write("        height: 1080px !important;\r\n");
      out.write("        border: 1px solid #fff;\r\n");
      out.write("        /* margin:auto; */\r\n");
      out.write("        /* z-index: 3; */\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translateX(-50%);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #ifwe {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 5%;\r\n");
      out.write("        left: 5%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    #text1 {\r\n");
      out.write("        /* 01글자 */\r\n");
      out.write("        position: absolute;\r\n");
      out.write("\r\n");
      out.write("        top: -1%;\r\n");
      out.write("        left: 13%;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #text2 {\r\n");
      out.write("        /* 반가워요글자 */\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 9%;\r\n");
      out.write("        left: 22.1%;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #text3 {\r\n");
      out.write("\r\n");
      out.write("        /* 어떤소모임 */\r\n");
      out.write("        position: absolute;\r\n");
      out.write("\r\n");
      out.write("        top: 12%;\r\n");
      out.write("        left: 22%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #text4 {\r\n");
      out.write("        /* kh achademy */\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 90%;\r\n");
      out.write("        left: 5%;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #cateallimg {\r\n");
      out.write("        /* 모든 이미지 위치 */\r\n");
      out.write("        position: relative;\r\n");
      out.write("        top: 35%;\r\n");
      out.write("        left: 13%;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .cateimg {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    #cateimg1 {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        background-image: url(../resources/images/selectcate/cate1.png);\r\n");
      out.write("        width: 540px;\r\n");
      out.write("        height: 495px;\r\n");
      out.write("        background-color: black;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #cateimg2 {\r\n");
      out.write("\r\n");
      out.write("        background-image: url(../resources/images/selectcate/cate2.png);\r\n");
      out.write("        position: relative;\r\n");
      out.write("        left: 20px;\r\n");
      out.write("        width: 540px;\r\n");
      out.write("        height: 495px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #cateimg3 {\r\n");
      out.write("\r\n");
      out.write("        position: relative;\r\n");
      out.write("        left: 39px;\r\n");
      out.write("        background-image: url(../resources/images/selectcate/cate3.png);\r\n");
      out.write("        width: 540px;\r\n");
      out.write("        height: 495px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .cateimg {\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        border-radius: 70px;\r\n");
      out.write("        background-color: black;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    #allcircle {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 26%;\r\n");
      out.write("        left: 80%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .circle {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        width: 15px;\r\n");
      out.write("        height: 15px;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        border-radius: 100%;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #circle1 {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        /* background-color: blue; */\r\n");
      out.write("        left: 0%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #circle2 {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        left: 25%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #circle3 {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #blackfilter1 {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        width: 540px;\r\n");
      out.write("        height: 495px;\r\n");
      out.write("        border-radius: 70px;\r\n");
      out.write("        opacity: 0.4;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #blackfilter2 {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        border-radius: 70px;\r\n");
      out.write("        width: 540px;\r\n");
      out.write("        height: 495px;\r\n");
      out.write("        opacity: 0.4;\r\n");
      out.write("        /* position: relative;\r\n");
      out.write("    left: 20px;\r\n");
      out.write("     */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #blackfilter3 {\r\n");
      out.write("        border-radius: 70px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        width: 540px;\r\n");
      out.write("        height: 495px;\r\n");
      out.write("        opacity: 0.4;\r\n");
      out.write("        /* position: relative;\r\n");
      out.write("    left: 39px; */\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .blackfilter {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .var1 {\r\n");
      out.write("\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 15%;\r\n");
      out.write("        left: 12%;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 35px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        z-index: 6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .var2 {\r\n");
      out.write("\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 70%;\r\n");
      out.write("        left: 11%;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        line-height: 30px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        z-index: 6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .var3 {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 70%;\r\n");
      out.write("        left: 73%;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("\r\n");
      out.write("        line-height: 30px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        z-index: 6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .cateimg:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #fontcircle1 {\r\n");
      out.write("\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 36%;\r\n");
      out.write("        left: 48%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #cicleallowright {\r\n");
      out.write("\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        size: 800px;\r\n");
      out.write("        z-index: 9;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    p{\r\n");
      out.write("        font-family : 'Godo'\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .whitevar{\r\n");
      out.write("\r\n");
      out.write("    position: absolute;\r\n");
      out.write("        height: 10px;\r\n");
      out.write("        width: 50px;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        left: 13%;\r\n");
      out.write("        top: 13%;\r\n");
      out.write("        z-index: 10;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .background-class{\r\n");
      out.write("        background-color: black;\r\n");
      out.write("    }\r\n");
      out.write("    .background-color{\r\n");
      out.write("        background-color: #2756a6;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- <img src=\"image/bmg.png\" alt=\"\" width=\"200px\" height=\"150px\"> -->\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div id=\"ifwe\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/index/logo_black.png\" alt=\"\" width=\"80\" height=\"35\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <p style=\"font-size: 85pt;\" id=\"text1\">01</p>\r\n");
      out.write("        <p style=\"font-size: 25pt;\" id=\"text2\">반가워요!</p>\r\n");
      out.write("        <p style=\"font-size: 35pt;\" id=\"text3\">\r\n");
      out.write("            어떤 소모임에<br>가입하고 싶으신가요?\r\n");
      out.write("        </p>\r\n");
      out.write("        <div id=\"allcircle\">\r\n");
      out.write("            <div class=\"circle\" id=\"circle1\"></div>\r\n");
      out.write("            <div class=\"circle\" id=\"circle2\"></div>\r\n");
      out.write("            <div class=\"circle\" id=\"circle3\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("        <div id=\"cateallimg\">\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"cateimg1\" class=\"cateimg\">\r\n");
      out.write("                <div class=\"whitevar\"></div>\r\n");
      out.write("                <div class=\"blackfilter background-class\" id=\"blackfilter1\"></div>\r\n");
      out.write("                <p class=\"var1\">공연&nbsp;<i class=\"fa fa-circle fa-xs\" style=\"font-size:0.2rem\"\r\n");
      out.write("                    id=\"fontcircle1\"></i>&nbsp; 전시\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"var2\">내 취향에 맞는 공연,전시,뮤지컬을</p>\r\n");
      out.write("                <p class=\"var2\"><br>소모임을 만들어 함께 즐겨보세요 </p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"var3\"><i class=\"far fa-arrow-alt-circle-right fa-4x\"></i></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- <img src=\"image/cate1.png\" alt=\"\" width=\"540px\" height=\"495px\"  >  -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"cateimg2\" class=\"cateimg\">\r\n");
      out.write("                <div class=\"whitevar\"></div>\r\n");
      out.write("                <div class=\"blackfilter background-class\" id=\"blackfilter2\"></div>\r\n");
      out.write("                <p class=\"var1\">스터디</p>\r\n");
      out.write("                <p class=\"var2\">혼자 공부하는게 어렵고 막막하다면</p>\r\n");
      out.write("                <p class=\"var2\"><br>소모임을 통해 시작해 보세요!</p>\r\n");
      out.write("                <!-- <img src=\"image/cate2.png\" alt=\"\" width=\"540px\" height=\"495px\"  > -->\r\n");
      out.write("\r\n");
      out.write("                <p class=\"var3\"><i class=\"far fa-arrow-alt-circle-right fa-4x\"></i></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div id=\"cateimg3\" class=\"cateimg\">\r\n");
      out.write("                <div class=\"whitevar\"></div>\r\n");
      out.write("                <!-- <img src=\"image/cate3.png\" alt=\"\" width=\"540px\" height=\"495px\" > -->\r\n");
      out.write("\r\n");
      out.write("                <p class=\"var1\">음악&nbsp;<i class=\"fa fa-circle fa-xs\" style=\"font-size:0.2rem\"\r\n");
      out.write("                        id=\"fontcircle1\"></i>&nbsp; 댄스</p>\r\n");
      out.write("                <p class=\"var2\">내가 좋아하는 음악과 춤을</p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"var2\"><br>즐거운 사람들과 함께 만들어 가요!</p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"var3\"><i class=\"far fa-arrow-alt-circle-right fa-4x\"></i></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"blackfilter background-class\" id=\"blackfilter3\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"allblackfilter\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <p style=\"font-size: 12pt;\" id=\"text4\">kh academy</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>    \r\n");
      out.write("    $(function(){\r\n");
      out.write("        \r\n");
      out.write("        $(\".cateimg\").hover(function(){\r\n");
      out.write("            $(this).children(\".blackfilter\").removeClass(\"background-class\");\r\n");
      out.write("            var thisid = $(this).attr(\"id\");\r\n");
      out.write("            if(thisid == 'cateimg1'){\r\n");
      out.write("                $(\"#circle1\").addClass(\"background-color\");\r\n");
      out.write("            }\r\n");
      out.write("            if(thisid == 'cateimg2'){\r\n");
      out.write("                $(\"#circle2\").addClass(\"background-color\");\r\n");
      out.write("            }\r\n");
      out.write("            if(thisid == 'cateimg3'){\r\n");
      out.write("                $(\"#circle3\").addClass(\"background-color\");\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        },function(){\r\n");
      out.write("            $(this).find(\".blackfilter\").addClass(\"background-class\");\r\n");
      out.write("            var thisid = $(this).attr(\"id\");\r\n");
      out.write("            if(thisid == 'cateimg1'){\r\n");
      out.write("                $(\"#circle1\").removeClass(\"background-color\");\r\n");
      out.write("            }\r\n");
      out.write("            if(thisid == 'cateimg2'){\r\n");
      out.write("                $(\"#circle2\").removeClass(\"background-color\");\r\n");
      out.write("            }\r\n");
      out.write("            if(thisid == 'cateimg3'){\r\n");
      out.write("                $(\"#circle3\").removeClass(\"background-color\");\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        $(\".cateimg\").click(function(){\r\n");
      out.write("        \tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberenroll.do\";\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
