/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-15 14:59:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1583844248000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Main</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main/afterLoginCommon.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/5e1e16b3f4.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/748cfe3a61.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Fredoka+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main/afterLogin-css.css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/mainInclude.jsp", out, false);
      out.write("\r\n");
      out.write("\t  <section>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <article class=\"first\">\r\n");
      out.write("                <div class=\"slide\">\r\n");
      out.write("                    <input type=\"radio\" name=\"pos\" id=\"pos1\" checked>\r\n");
      out.write("                    <input type=\"radio\" name=\"pos\" id=\"pos2\">\r\n");
      out.write("                    <input type=\"radio\" name=\"pos\" id=\"pos3\">\r\n");
      out.write("                    <input type=\"radio\" name=\"arrow\" id=\"next\" checked>\r\n");
      out.write("                    <input type=\"radio\" name=\"arrow\" id=\"down\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li>\r\n");
      out.write("                          <div class=\"li-content\">\r\n");
      out.write("                            <div class=\"li-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/banner.png\" alt=\"\">\r\n");
      out.write("                                <div class=\"search font-kor\">\r\n");
      out.write("                                    <div class=\"search-title\">\r\n");
      out.write("                                        <p style=\"font-size: 40px;\">나와 관심사가 같은 친구,</p>\r\n");
      out.write("                                        <p style=\"font-size:50px;font-weight: 3000;\" class=\"font-eng\">ifwe에서 만나보세요</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"search-content font-kor\">\r\n");
      out.write("                                        <p class=\"p-class\">회원님의 관심사 어쩌고</p>\r\n");
      out.write("                                        <p class=\"p-class\">회원님의 관심사 어쩌고</p>\r\n");
      out.write("                                        <p class=\"p-class\">회원님의 관심사 어쩌고</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"search-btn font-kor\" style=\"margin-top: 10%;\">\r\n");
      out.write("                                        <button class=\"font-kor\">소모임 검색하기</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <div class=\"li-content\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/banner.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <div class=\"li-content\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main/banner.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <p class=\"bullet\">\r\n");
      out.write("                      <label for=\"pos1\">1</label>\r\n");
      out.write("                      <label for=\"pos2\">2</label>\r\n");
      out.write("                      <label for=\"pos3\">3</label>\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("            </article>\r\n");
      out.write("    \r\n");
      out.write("            <article class=\"second\"> \r\n");
      out.write("                <div class=\"one\">\r\n");
      out.write("                    <div class=\"one-one\">\r\n");
      out.write("                        <div class=\"card font-kor\">\r\n");
      out.write("                            <p style=\"padding: 7%;margin-left: 10%; color: white;\">내 소모임</p> \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"list\">\r\n");
      out.write("                            <ul class=\"font-kor list-ul\">\r\n");
      out.write("                                <li> <p>윙스터디 모임</p> </li>\r\n");
      out.write("                                <li><p>윙스터디 모임</p></li>\r\n");
      out.write("                                <li><p>윙스터디 모임</p></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"one-two\">\r\n");
      out.write("                       <div class=\"linebar\"></div>\r\n");
      out.write("                       <div class=\"post\"><p class=\"font-kor\"><span style=\"font-weight: bolder;\">소모임</span>을</p> <p class=\"font-kor\">직접 만들어 보세요!</p></div>\r\n");
      out.write("                       <div class=\"make-btn\">\r\n");
      out.write("                           <input type=\"button\" value=\"소모임 만들기\" class=\"font-kor\">\r\n");
      out.write("                       </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"two\">\r\n");
      out.write("                    <div class=\"two-title font-kor\">\r\n");
      out.write("                        <p style=\"color: white; margin-left:5%; font-size: 20px;padding: 4%;\">주간 베스트글 </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"two-content font-kor\">\r\n");
      out.write("                        <div class=\"post-container\">\r\n");
      out.write("                            <div class=\"number font-kor\">01</div>\r\n");
      out.write("                                <div class=\"posts\">\r\n");
      out.write("                                    <p class=\"post1\">망고스터디</p>\r\n");
      out.write("                                    <p class=\"post2\">스터디 카페추천드려요</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <hr class=\"two-hr\" noshade>\r\n");
      out.write("                        <div class=\"post-container\">\r\n");
      out.write("                            <div class=\"number font-kor\">02</div>\r\n");
      out.write("                                <div class=\"posts\">\r\n");
      out.write("                                    <p class=\"post1\">망고스터디</p>\r\n");
      out.write("                                    <p class=\"post2\">스터디 카페 추천드려요</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <hr class=\"two-hr\" noshade>\r\n");
      out.write("                        <div class=\"post-container\">\r\n");
      out.write("                            <div class=\"number font-kor\">03</div>\r\n");
      out.write("                                <div class=\"posts\">\r\n");
      out.write("                                    <p class=\"post1\">망고스터디</p>\r\n");
      out.write("                                    <p class=\"post2\">스터디 카페 추천드려요</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"three\">\r\n");
      out.write("                    <div class=\"three-title font-kor\">\r\n");
      out.write("                        <p style=\"color: white; font-size: 20px; margin-left: 5%;padding: 3%;\">이런 모임은 어때요? </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"three-content font-kor\">\r\n");
      out.write("                        <div class=\"three-container\">\r\n");
      out.write("                            <div class=\"three-div\">\r\n");
      out.write("                                <div class=\"three-img\">\r\n");
      out.write("                                    <img src=\"./images/ex2.jpg\" alt=\"\" width=\"120px\" height=\"120px\" style=\"border-radius: 75px;\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"three-posts\">\r\n");
      out.write("                                    <div class=\"three-post1\">@english_4965</div>\r\n");
      out.write("                                    <div class=\"three-post2\">기초 영어회화반</div>\r\n");
      out.write("                                    <div class=\"three-post3\"><i class=\"fas fa-map-marker-alt\"></i>&nbsp;&nbsp;서울/경기</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"three-btn\">\r\n");
      out.write("                                    <input type=\"button\" value=\"자세히 보기\" class=\"font-kor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"three-div\">\r\n");
      out.write("                                <div class=\"three-img\">\r\n");
      out.write("                                    <img src=\"./images/ex2.jpg\" alt=\"\" width=\"120px\" height=\"120px\" style=\"border-radius: 75px;\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"three-posts\">\r\n");
      out.write("                                    <div class=\"three-post1\">@english_4965</div>\r\n");
      out.write("                                    <div class=\"three-post2\">기초 영어회화반</div>\r\n");
      out.write("                                    <div class=\"three-post3\"><i class=\"fas fa-map-marker-alt\"></i>&nbsp;&nbsp;서울/경기</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"three-btn\">\r\n");
      out.write("                                    <input type=\"button\" value=\"자세히 보기\" class=\"font-kor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </article>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
