/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-15 12:36:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1583844248000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspacese/spring_workspace/Ifwe.0.1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_fmt_005frequestEncoding_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>if we</title>\r\n");
      out.write("    <script src=\"resources/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/index/login.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/226b55f414.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- 한글 폰트 -->\r\n");
      out.write("<style>\r\n");
      out.write("    @font-face { font-family: 'GmarketSansLight'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansLight.woff') format('woff'); font-weight: normal; font-style: normal; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 영문폰트 -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Fredoka+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#loginbutton\").click(function(){\r\n");
      out.write("\t\t$(\".back\").css(\"display\",\"inline-block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#startbutton\").click(function(){\r\n");
      out.write("\t\t$(\".back\").css(\"display\",\"inline-block\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".back\").click(function(e){\r\n");
      out.write("\t\tif($(e.target).is(\".back\")){\r\n");
      out.write("\t\t$(\".back\").css(\"display\",\"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#joinbutton\").click(function(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/selectcate.do\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".main-kor{\r\n");
      out.write("    font-family: 'GmarketSansLight';\r\n");
      out.write("}\r\n");
      out.write(".main-eng{\r\n");
      out.write("    font-family: 'Fredoka One';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("/* body */\r\n");
      out.write("*{\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    margin: 0px;    \r\n");
      out.write("    color:#3b3b3b;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write(".main-body{    \r\n");
      out.write("    width: 1920px;\r\n");
      out.write("    height: 1280px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    /* border: 1px solid #61d4b3;     */\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    left:50%;\r\n");
      out.write("    transform: translate(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* wrapper main div */\r\n");
      out.write(".wrapper-main{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 1660px;\r\n");
      out.write("    height: 1040px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    /* border: 1px solid #fdd365; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* background circle */\r\n");
      out.write("\r\n");
      out.write(".main-div-bg{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    z-index: -1;\r\n");
      out.write("    left: -25%;\r\n");
      out.write("    top: -35%;\r\n");
      out.write("    width:1210px;\r\n");
      out.write("    height:1250px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write(".main-div-bg img{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;    \r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* header */\r\n");
      out.write(".wrapper-main header{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    /* border: 1px solid #fb8d62; */\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("}\r\n");
      out.write(".main-header-ul{    \r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    /* border: 1px solid #fd2eb3; */\r\n");
      out.write("}\r\n");
      out.write(".main-header-ul li{    \r\n");
      out.write("    width: 65px;\r\n");
      out.write("    height: 100%;    \r\n");
      out.write("    /* border: 1px solid black; */\r\n");
      out.write("}\r\n");
      out.write(".main-header-ul li:nth-child(1){    \r\n");
      out.write("     float: left;\r\n");
      out.write("}\r\n");
      out.write(".main-header-ul li:not(:nth-child(1)){    \r\n");
      out.write("     float: right;\r\n");
      out.write("     text-align: center;\r\n");
      out.write("     font-size: 27px;\r\n");
      out.write("}\r\n");
      out.write(".main-header-ul li:not(:nth-child(2n-1)){\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".main-header-ul li .fa-circle{\r\n");
      out.write("    font-size: 8px;\r\n");
      out.write("}\r\n");
      out.write(".main-header-ul li img{\r\n");
      out.write("    width: 80px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* section */\r\n");
      out.write(".main-section{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 94%;\r\n");
      out.write("    /* border: 1px solid red; */\r\n");
      out.write("    display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* article box left*/\r\n");
      out.write(".main-section article{\r\n");
      out.write("    flex: 1;    \r\n");
      out.write("    height: 100%;\r\n");
      out.write("    /* border: 1px solid #413c69; */\r\n");
      out.write("}\r\n");
      out.write(".main-section article:first-child{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 500px;\r\n");
      out.write("    height: 51%;\r\n");
      out.write("    top: 51%;\r\n");
      out.write("    transform: translateY(-50%);        \r\n");
      out.write("}\r\n");
      out.write(".main-section article:first-child div{    \r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    /* border: 1px red solid; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-section article:first-child div:first-child p:nth-child(1){\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write(".main-section article:first-child div:nth-child(2) {    \r\n");
      out.write("    margin-top: 5.2%;\r\n");
      out.write("}\r\n");
      out.write(".main-section article:first-child div:nth-child(2) p{    \r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".main-section article:first-child div:nth-child(3){\r\n");
      out.write("    margin-top: 5.2%;\r\n");
      out.write("}\r\n");
      out.write(".main-section article:first-child div:nth-child(3) p{\r\n");
      out.write("    margin-top: 2%;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    opacity: 0.65;    \r\n");
      out.write("}\r\n");
      out.write(".main-section article:first-child div:nth-child(4){\r\n");
      out.write("    margin-top: 6.5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 시작하기 button */\r\n");
      out.write(".main-btn-start{\r\n");
      out.write("    width: 320px;\r\n");
      out.write("    height: 82px;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    background: #ffc862;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 25px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    font-weight: bold;    \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* article box right*/\r\n");
      out.write(".main-section article:last-child img{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    top: 22%;\r\n");
      out.write("    z-index: -2;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("/* main footer */\r\n");
      out.write(".main-footer{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 2%;\r\n");
      out.write("    /* border: 1px solid #eab9c9; */\r\n");
      out.write("}\r\n");
      out.write(".main-footer p{\r\n");
      out.write("    color: #3b3b3b;\r\n");
      out.write("    opacity: 0.65;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"main-body main-kor\">\r\n");
      out.write("        <div class=\"wrapper-main\">    \r\n");
      out.write("            <div class=\"main-div-bg\">\r\n");
      out.write("                <img src=\"resources/images/index/main_circle.png\" alt=\"circle-grad\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <header>\r\n");
      out.write("                <ul class=\"main-header-ul main-eng\">\r\n");
      out.write("                    <li><img src=\"resources/images/index/logo_black.png\" alt=\"\"></li>\r\n");
      out.write("                    <li id=\"joinbutton\">join</li>\r\n");
      out.write("                    <li><i class=\"fas fa-circle\"></i></li>\r\n");
      out.write("                    <li id=\"loginbutton\">login</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </header>\r\n");
      out.write("            <section class=\"main-section\">\r\n");
      out.write("                <article>\r\n");
      out.write("                    <div><p>나와 관심사가 같은 친구,</p></div>                    \r\n");
      out.write("                    <div><p><img src=\"resources/images/index/logo_black.png\" \r\n");
      out.write("                    \t\tstyle=\"width:115px; height:50px;\" alt=\"\"> 에서 만나보세요</p></div>                    \r\n");
      out.write("                    <div>\r\n");
      out.write("                    \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/mainPage.do\">메인페이지</a>\r\n");
      out.write("                        <p>회원님의 관심사에 맞는 친구모임을</p>\r\n");
      out.write("                        <p>찾아보세요. 나와 같은 취미의 친구들과</p>\r\n");
      out.write("                        <p>즐거운 시간을 if we에서 보내보세요.</p>\r\n");
      out.write("                    </div>                    \r\n");
      out.write("                    <div><button type=\"button\" class=\"main-btn-start\" id=\"startbutton\">시작하기</button></div>                                                                                \r\n");
      out.write("                </article>\r\n");
      out.write("                <article>\r\n");
      out.write("                    <img src=\"resources/images/index/main_img_03.png\" alt=\"\">                    \r\n");
      out.write("                </article>\r\n");
      out.write("            </section>\r\n");
      out.write("            <footer class=\"main-footer\">\r\n");
      out.write("                <p>kh academy</p>\r\n");
      out.write("            </footer>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"back\">\r\n");
      out.write("        <div class=\"login-container\">\r\n");
      out.write("            <div class=\"login-container-box\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"login-title\">\r\n");
      out.write("                    <p>로그인</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"login-input\">\r\n");
      out.write("                    <i class=\"far fa-user\"></i> <input class=\"input-box\" type=\"text\" name=\"userid\" id=\"userid\" placeholder=\"아이디\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"login-input\">\r\n");
      out.write("                    <i class=\"fas fa-lock\"></i> <input class=\"input-box\" type=\"password\" name=\"password\" id=\"password\" placeholder=\"비밀번호\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"login-extra\">\r\n");
      out.write("                    <a href=\"\">아이디 | 비밀번호 찾기</a> <div class=\"saveid-container\"><input type=\"checkbox\" name=\"saveid\" id=\"saveid\"><label for=\"saveid\">아이디 저장</label></div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"login-area\">\r\n");
      out.write("                    로그인\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"login-naver-box\">\r\n");
      out.write("                    <button id=\"naver\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"login-register\">\r\n");
      out.write("                    <p>아직 회원이 아니신가요?</p> <button id=\"register\">회원가입</button> \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005frequestEncoding_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:requestEncoding
    org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag _jspx_th_fmt_005frequestEncoding_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag) _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag.class);
    boolean _jspx_th_fmt_005frequestEncoding_005f0_reused = false;
    try {
      _jspx_th_fmt_005frequestEncoding_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005frequestEncoding_005f0.setParent(null);
      // /index.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005frequestEncoding_005f0.setValue("utf-8");
      int _jspx_eval_fmt_005frequestEncoding_005f0 = _jspx_th_fmt_005frequestEncoding_005f0.doStartTag();
      if (_jspx_th_fmt_005frequestEncoding_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005frequestEncoding_005f0);
      _jspx_th_fmt_005frequestEncoding_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005frequestEncoding_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005frequestEncoding_005f0_reused);
    }
    return false;
  }
}
