/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-15 13:59:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class clubCreate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Club Create</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Fredoka+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main/afterLoginCommon.css\">\r\n");
      out.write("<style>\r\n");
      out.write("    .thin-font{\r\n");
      out.write("        font-weight: 100;\r\n");
      out.write("    }\r\n");
      out.write("    *{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    @font-face { \r\n");
      out.write("        font-family: 'GmarketSansLight'; \r\n");
      out.write("        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansLight.woff') format('woff'); \r\n");
      out.write("        font-weight: normal; \r\n");
      out.write("        font-style: normal; \r\n");
      out.write("    }\r\n");
      out.write("    .font-kor{\r\n");
      out.write("        font-family: 'GmarketSansLight'; \r\n");
      out.write("    }\r\n");
      out.write("    #container{ \r\n");
      out.write("        margin: 6%;\r\n");
      out.write("        height: 1160px;\r\n");
      out.write("        overflow:auto; \r\n");
      out.write("    }\r\n");
      out.write("    .number{\r\n");
      out.write("        font-size: 35px;\r\n");
      out.write("        display: inline;\r\n");
      out.write("        margin-right: 4%;\r\n");
      out.write("    }\r\n");
      out.write("    .title{\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("        display: inline;\r\n");
      out.write("        font-weight: 100;\r\n");
      out.write("    }\r\n");
      out.write("    .inputs{\r\n");
      out.write("        margin-left: 6%;\r\n");
      out.write("        margin-top: 2%;\r\n");
      out.write("    }\r\n");
      out.write("    .inputs .buttons{\r\n");
      out.write("        border: 1px solid #ffc862;\r\n");
      out.write("        background-color: #ffc862;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        outline: 0;\r\n");
      out.write("        width: 195px;\r\n");
      out.write("        height: 45px;\r\n");
      out.write("        margin: 0 2% 0 0 ;\r\n");
      out.write("    }\r\n");
      out.write("    .info-container{\r\n");
      out.write("        margin-bottom:5%\r\n");
      out.write("    }\r\n");
      out.write("    .span-post{\r\n");
      out.write("        color:rgb(235, 42, 14); \r\n");
      out.write("        margin-left: 5%;\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("    }\r\n");
      out.write("    .span-people{\r\n");
      out.write("        color:rgb(56, 209, 9);; \r\n");
      out.write("        margin-left: 5%;\r\n");
      out.write("        font-size: 25px\r\n");
      out.write("    }\r\n");
      out.write("    .input-text{\r\n");
      out.write("        width: 970px;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        outline: 0;\r\n");
      out.write("        border: 0;\r\n");
      out.write("        background-color: #ebebeb;;\r\n");
      out.write("    }\r\n");
      out.write("    .input-file{\r\n");
      out.write("        width: 700px;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        outline: 0;\r\n");
      out.write("        border: 0;\r\n");
      out.write("        background-color: #ebebeb;;\r\n");
      out.write("    }\r\n");
      out.write("    .selects{\r\n");
      out.write("        width: 345px;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        padding: 1%;\r\n");
      out.write("        outline: 0;\r\n");
      out.write("        -webkit-appearance: none; -moz-appearance: none;\r\n");
      out.write("        background: url('down-arrow.png') no-repeat 95% 50%;\r\n");
      out.write("    }\r\n");
      out.write("    .upload-hidden{\r\n");
      out.write("        width: 0;\r\n");
      out.write("        height: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        border: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .file-label{\r\n");
      out.write("        margin-left: 3%;\r\n");
      out.write("        padding:4% 5%;\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        background-color: #ffc862;;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        color: white;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .c-btn{\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        height: 65px;\r\n");
      out.write("        background-color: rgb(50, 87, 161);\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        border: 1px solid rgb(50, 87, 161);\r\n");
      out.write("        outline: 0;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/mainInclude.jsp", out, false);
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div id=\"container\" >\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <div id=\"first\" class=\"info-container\">\r\n");
      out.write("                        <div class=\"number font-kor\">01</div>\r\n");
      out.write("                        <div class=\"font-kor title thin-font\">어떤 소모임을 만드실건가요?</div>\r\n");
      out.write("                        <div class=\"inputs\">\r\n");
      out.write("                            <input type=\"button\" value=\"공연/전시\" name=\"concert\" class=\"font-kor buttons\">\r\n");
      out.write("                            <input type=\"button\" value=\"스터디\" name=\"concert\" class=\"font-kor buttons\">\r\n");
      out.write("                            <input type=\"button\" value=\"음악/댄스\" name=\"concert\" class=\"font-kor buttons\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"second\" class=\"info-container\">\r\n");
      out.write("                        <div class=\"number font-kor\">02</div>\r\n");
      out.write("                        <div class=\"font-kor title thin-font\">소모임 키워드를 4개이하로 입력해주세요</div>\r\n");
      out.write("                        <span class=\"font-kor span-post thin-font\">단어 앞에 #을 붙여서 입력하세요</span>\r\n");
      out.write("                        <div class=\"inputs\">\r\n");
      out.write("                            <input type=\"text\" name=\"keywords\" class=\"font-kor input-text thin-font\" placeholder=\"       예)   #영어 #영어회화 #스터디모임 #서울/경기\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"third\" class=\"info-container\">\r\n");
      out.write("                        <div class=\"number font-kor\">03</div>\r\n");
      out.write("                        <div class=\"font-kor title thin-font\">소모임명을 정해주세요</div>\r\n");
      out.write("                        <div class=\"inputs\">\r\n");
      out.write("                            <input type=\"text\" name=\"somoim-name\" class=\"font-kor input-text thin-font\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"fourth\" class=\"info-container\">\r\n");
      out.write("                        <div class=\"number font-kor\">04</div>\r\n");
      out.write("                        <div class=\"font-kor title thin-font\">소모임 소개글을 입력하세요</div>\r\n");
      out.write("                        <div class=\"inputs\">\r\n");
      out.write("                            <input type=\"text\" name=\"somoim-info\" class=\"font-kor input-text thin-font\" >\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"fifth\" class=\"info-container\">\r\n");
      out.write("                        <div class=\"number font-kor\">05</div>\r\n");
      out.write("                        <div class=\"font-kor title thin-font\">소모임 주 활동지역을 설정해주세요</div>\r\n");
      out.write("                        <div class=\"inputs\">\r\n");
      out.write("                            <select name=\"loc\" id=\"\" class=\"selects thin-font font-kor\">\r\n");
      out.write("                                <option value=\"capital\">서울/경기</option>\r\n");
      out.write("                                <option value=\"\">부산</option>\r\n");
      out.write("                                <option value=\"\">대전</option>\r\n");
      out.write("                                <option value=\"\">대구</option>\r\n");
      out.write("                                <option value=\"\">울산</option>\r\n");
      out.write("                                <option value=\"\">강원</option>\r\n");
      out.write("                                <option value=\"\">충북</option>\r\n");
      out.write("                                <option value=\"\">충남</option>\r\n");
      out.write("                                <option value=\"\">경북</option>\r\n");
      out.write("                                <option value=\"\">경남</option>\r\n");
      out.write("                                <option value=\"\">전남</option>\r\n");
      out.write("                                <option value=\"\">전북</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"sixth\" class=\"info-container\">\r\n");
      out.write("                        <div class=\"number font-kor\">06</div>\r\n");
      out.write("                        <div class=\"font-kor title thin-font\">소모임 인원수를 정해주세요</div>\r\n");
      out.write("                        <div class=\"inputs\">\r\n");
      out.write("                            <select name=\"loc\" id=\"\" class=\"selects thin-font font-kor\">\r\n");
      out.write("                                <option value=\"\">1~10</option>\r\n");
      out.write("                                <option value=\"\">11~20</option>\r\n");
      out.write("                                <option value=\"\">20~25</option>                   \r\n");
      out.write("                            </select>\r\n");
      out.write("                            <span class=\"font-kor thin-font span-people\">최대 25명</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"seventh\" class=\"info-container\">\r\n");
      out.write("                        <div class=\"number font-kor\">07</div>\r\n");
      out.write("                        <div class=\"font-kor title thin-font\">소모임 배너에 들어갈 대표이미지를 지정해주세요</div>\r\n");
      out.write("                        <div class=\"inputs\">\r\n");
      out.write("                            <input name=\"fileName\" id=\"\" class=\"font-kor input-file thin-font\">\r\n");
      out.write("                            <label for=\"input-file\" class=\"file-label font-kor\">파일첨부</label>\r\n");
      out.write("                            <input type=\"file\" id=\"input-file\" class=\"upload-hidden\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"create-btn\" class=\"inputs\">\r\n");
      out.write("                        <input type=\"button\" value=\"소모임 생성\" class=\"font-kor thin-font c-btn\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
